ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module
  db:
    jdbcUrl: "jdbc:postgresql://localhost:5432/simple"
    dbUser: postgres
    dbPassword: 11
